artifacts :
  artifact_folder_name: artifacts

  test_data_folder_name: test_data
  test_data_name: 1.xlsx

  Corrected_Header_Data_Folder_name: Corrected_Header_Data_Folder
  Corrected_Header_Data_File_name: 

  transformed_data_folder_name: transformed_data
  transformed_data_name: transformed_data.csv
