 # uncomment below lines to use CML

name: DVC-project
 
on: [push]
 
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          pyhon-version: '3.7'
      - name: Install dependencies
        env:
          REPO_TOKEN: ${{ secrets._GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_VENDOR_PROJECT_123 }}
          